services:
  frontend:
    container_name: nextjs-frontend
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    labels:
      - dev.dozzle.name=frontend-nextjs
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - /app/node_modules
