services:
  frontend:
    container_name: nextjs-frontend
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    labels:
      - dev.dozzle.name=frontend-nextjs
    ports:
      - "3000:3000"
