services:
  frontend:
    container_name: nextjs-frontend
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    labels:
      - dev.dozzle.name=frontend-nextjs
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
