export enum RESTServerRoute {
  REST_AUTH_SETTINGS = 'settings/auth',
  REST_PROFILES = 'profiles',
  REST_PROFILE = 'profiles/:id',
  REST_PROFILE_MATCHES = 'profiles/matches',
  REST_BOOSTER = 'booster',
  REST_TEN_BOOSTERS = 'booster/10',
  REST_AVAILABLE_PACKS = 'booster/list',
  REST_PROFILES_IMAGES = 'profiles/image',
  REST_MATCHES = 'matches',
  REST_MATCHES_PENDING = 'matches/pending',
  REST_MATCHES_SENT = 'matches/sent',
  REST_MATCHES_DETAILS = 'matches/details/:id',
  REST_MATCHES_LIKE = 'matches/like/:id',
  REST_MATCHES_PASS = 'matches/pass/:id',
  // Admin routes
  REST_PROFILES_ALL = 'profiles/all',
  REST_ADMIN_BAN_USER = 'profiles/:userId/ban',
  REST_ADMIN_UNBAN_USER = 'profiles/:userId/unban',
  REST_ADMIN_USER_PROFILE = 'profiles/:userId/profile',
}
